SIMD NF4: avoid error message on compiling w/ GNUC
error: ignoring attributes on template argument ‘__int128 unsigned’
is caused by GroupedValues<aint128>